services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=Pizza'
      - 'MONGO_INITDB_ROOT_PASSWORD=82232'
      - 'MONGO_INITDB_ROOT_USERNAME=ransuum'
    ports:
      - '27017'
