version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - JDBC_URI=${JDBC_URI}
    ports:
      - "8081:8081"

#    depends_on:
#      - postgres_db
#  postgres_db:
#    image: 'postgres:15-alpine'
#    container_name: postgresDB
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    restart: unless-stopped
