version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres:15-alpine'
    container_name: postgresDB
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
